### ISSUE TITLE
sha1sums out of date

### ISSUE THREAD

**Issue by jshholland** [andrewd18/df-lnp-installer#16]
It seems that the [Utility Plugins](http://dffd.wimbli.com/file.php?id=7248) have been updated, and so the checksums no longer match. I can't see the checksums anywhere officially on DFFD, but the file I downloaded locally is `5e68e93f7fd5e4301b6050c7b29790c4d59aeabb`. I updated the `sha1sums` file to match that, and everything seemed to work out ok.

**Comment by Easykill** [comment]
This helped me, thanks.

**Comment by andrewd18** [comment]
Wait, so standard practice on DFFD is to update the file but not create a new download link? That's frustrating. Now we're going to have tons of sha1sum errors any time a file gets updated. :(

Guess I'll have to create a --skip-checksums option or something like that for easier overrides.

**Comment by andrewd18** [comment]
The sha1sum has been updated as of 0.2.3.
