### ISSUE TITLE
Ubuntu 13.04 install cancellation

### ISSUE THREAD

**Issue by threeeyedmonkey** [andrewd18/df-lnp-installer#18]
requesting all changes
adding changesets
adding manifests
adding file changes
added 577 changesets with 4554 changes to 813 files (+2 heads)
updating to branch default
662 files updated, 0 files merged, 0 files removed, 0 files unresolved
sha1sum: sha1sums: No such file or directory
df-lnp-installer.sh: One or more file failed its checksum. Exiting.

**Comment by andrewd18** [comment]
Please provide me with the commands you typed to download and run the installer, complete with the prompt.

**Comment by threeeyedmonkey** [comment]
I created a new directory called df_linux and moved the df-lnp-installer-master.zip into it. Then i extracted the file and moved the df-lnp-installer.sh into the directory outside of the df-lnp-installer-master file. Then i ran this command ./df-lnp-installer.sh and told it to run in the df_linux directory. Hit enter and it gave me that message after lots of insatlling text.

**Comment by andrewd18** [comment]
> and moved the df-lnp-installer.sh into the directory outside of the df-lnp-installer-master file.

That was your problem. The df-lnp-installer.sh script is not standalone; it needs other files to be in known locations, files which come packaged with it. Because you moved the df-lnp-installer.sh file out from where it belonged, it failed to run properly.

Move the df-lnp-installer.sh back into the df-lnp-installer-master/ folder and try it again.

**Comment by threeeyedmonkey** [comment]
Thank you so much its working now, but can i open it without having to use the terminal somehow.

**Comment by andrewd18** [comment]
> can i open it without having to use the terminal somehow.

Yes. If you are using Unity you can follow these instructions: https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles

Have the .desktop file run the "startlnp" script, which lives wherever you told the df-lnp-installer to install Dwarf Fortress.
