### ISSUE TITLE
Compiling Dwarf Therapist failed.

### ISSUE THREAD

**Issue by etenie** [andrewd18/df-lnp-installer#22]
/bin/downloads/dwarftherapist'
df-lnp-installer.sh: Compiling Dwarf Therapist failed. Exiting.

**Comment by andrewd18** [comment]
What version of the script are you running? --version or -v should tell you.

Secondly, I'm going to need more output than those two lines to figure out what went wrong here. Please provide more info. Thanks.

**Comment by etenie** [comment]
Project MESSAGE: Release Mode
Project MESSAGE: Setting up for Linux
Project MESSAGE: Setting up for Linux Install
make: Entering directory `/home//bin/downloads/dwarftherapist'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4 -Iinc -Iinc/models -Iinc/grid_view -Iinc/docks -Iui -Ithirdparty/qtcolorpicker-2.6 -Ibin/release -Ibin/release -o bin/release/dfinstancelinux.o src/dfinstancelinux.cpp
make: g++: Command not found
make: *** [bin/release/dfinstancelinux.o] Error 127
make: Leaving directory`/home//bin/downloads/dwarftherapist'
df-lnp-installer.sh: Compiling Dwarf Therapist failed. Exiting

and by version do you mean of ubuntu? if so its 13.04

**Comment by andrewd18** [comment]
Nope, was asking about the version of the df-installer script, but that doesn't matter now as you've found the problem:

> g++: Command not found

This was an issue already reported in https://github.com/andrewd18/df-lnp-installer/issues/20, and will be fixed as part of the 0.3.0 release. In the meantime, please install the g++ package and run the script again. You may need to manually delete whatever folder you were trying to install to.

**Comment by etenie** [comment]
this is going to sound really stupid but how do i install the g++ package?

**Comment by andrewd18** [comment]
`sudo apt-get install g++` from the command line should do it. Alternately, use the Ubuntu Software Center or Synaptic to search for and install g++.

**Comment by andrewd18** [comment]
0.3.0 now has an explicit check for g++.
