### ISSUE TITLE
Some problems with compiling and running dwarf therapist

### ISSUE THREAD

**Issue by marvalis** [andrewd18/df-lnp-installer#25]
I have qt4 packages installed and I ran

Code: 
sudo apt-get install default-jre libsdl1.2debian:i386 libsdl-image1.2:i386 libsdl-ttf2.0-0:i386 libglu1-mesa:i386 libgtk2.0-0:i386 libopenal1:i386 libjpeg62:i386 git mercurial libqt4-dev qt4-qmake wget coreutils tar unzip unrar make g++ gcc patch xterm sed

But I still get issues.

Quote
    df-lnp-installer.sh: Your computer is missing the following programs or libraries: libQtCore libQtGui libQtNetwork libQtScript . Install them using your distribution's package manager or use --skip-deps to override. Exiting.

I imagine that it is because of a previous qt install. And right now I don't have the time or energy to figure out how to make qt working.

Quote
    src/dfinstancelinux.cpp:23:21: fatal error: QtWidgets: No such file or directory.

Here is the log from trying to run a pre-compiled dwarf therapist version:
2013-Oct-06 21:05:16.131 ERROR  core    No valid memory layouts found in the following directories... () [src/dfinstance.cpp:106](DFInstance)
2013-Oct-06 21:05:16.194 DEBUG  core    base_addr: 274048 HEX 42e80 [src/dfinstancelinux.cpp:324](find_running_copy)
2013-Oct-06 21:05:16.356 DEBUG  core    DF's checksum is "0xe966ee88" [src/dfinstancelinux.cpp:328](find_running_copy)
2013-Oct-06 21:05:16.356 DEBUG  core    DF's checksum is: "0xe966ee88" [src/dfinstance.cpp:876](get_memory_layout)
2013-Oct-06 21:05:16.356 DEBUG  core    Could not find layout for checksum "0xe966ee88" [src/dfinstance.cpp:883](get_memory_layout)
2013-Oct-06 21:05:16.356 INFO   core    Checking for layout for checksum:  "0xe966ee88" [src/mainwindow.cpp:396](check_for_layout)
2013-Oct-06 21:05:16.356 INFO   core    Dwarf fortress path: "/home/ron/Downloads/df_linux" [src/dfinstancelinux.cpp:335](find_running_copy)

I think the problem is with my QT4 installation, but I have no idea.

Any tips or ideas are welcome. Ask if you need more info about this specific issue.

Thanks.

**Comment by andrewd18** [comment]
What version of the script are you using? `df-lnp-installer.sh -v` should
tell you.

**Comment by marvalis** [comment]
Dwarf Fortress LNP Linux Installer
Version: 0.3.0

**Comment by andrewd18** [comment]
If I'm correct, this was resolved in 0.3.1. Please do a "git pull" to 
update your working copy, then try again.

**Comment by marvalis** [comment]
It managed to compile. Dwarf therapist, which would normally close down on me after start-up, simply works. As does the LNP pack. I don't know how you did it, but you got it to work. Pretty amazing. Coding this installer was a pretty dwarfly thing to do of you.

Thanks a heap. Now I can enjoy dwarf fortress in linux (with the tools to make it playable :P).
