### ISSUE TITLE
403 HTTP header upon executing script

### ISSUE THREAD

**Issue by codingpunk** [andrewd18/df-lnp-installer#28]
When I use this script to install DF, after resolving domain names and sending the HTTP requests it gives me back a 403 Forbidden error. It's a user agent problem as downloading the files from a browser works normally but regular wget's get this error without adding one. It seems fairly recent too as other people were able to use this fine without any problems.

To make this work for me, I edited the code at local WGET_OPTIONS= to include a user agent so that the server would allow the download to continue. 

You might want to edit the script and add a user agent argument so that other folks don't run into this any more.

local WGET_OPTIONS="-U Mozilla/14.0 -nc --directory-prefix=$DOWNLOAD_DIR"

**Comment by andrewd18** [comment]
Resolved in 0.4.0-dev branch.
