### ISSUE TITLE
Checksum error for dfhack

### ISSUE THREAD

**Issue by SirDifferential** [andrewd18/df-lnp-installer#3]
Using Debian Stable (Wheezy):

downloads/df_34_11_linux.tar.bz2: OK
downloads/dfhack-0.34.11-r3-Linux.tar.gz: FAILED
downloads/lazy-newbpack-linux-0.5.3-SNAPSHOT-20130822-1652.tar.bz2: OK
downloads/Utility_Plugins_v0.35-Windows-0.34.11.r3.zip.zip: OK
downloads/soundSense_42_186.zip: OK
downloads/Phoebus_34_11v01.zip: OK
downloads/CLA_graphic_set_v15-STANDALONE.rar: OK
downloads/Ironhand16 upgrade 0.73.4.zip: OK
downloads/Mayday 34.11.zip: OK
downloads/[16x16] Obsidian (v.0.8).zip: OK
downloads/[16x16] Spacefox 34.11v1.0.zip: OK
downloads/JollyBastion34-10v5.zip: OK
sha1sum: WARNING: 1 computed checksum did NOT match
df-lnp-installer.sh: One or more file failed its checksum. Exiting.

someone@xxx:~/df-lnp-installer$ sha1sum downloads/dfhack-0.34.11-r3-Linux.tar.gz
7bcf0bf5fc28d3d896addf6a4e8e53dc3756f46a  downloads/dfhack-0.34.11-r3-Linux.tar.gz

^ Github breaks formatting for sha1sum, but the "commit link" here is the checksum I get for running sha1sum.

**Comment by doomchild** [comment]
I have the same problem on Mint Nadia.

**Comment by drfragment** [comment]
Same problem here.
