### ISSUE TITLE
Auto folder detection + cleanup deleted .local/share.

### ISSUE THREAD

**Issue by andrewd18** [andrewd18/df-lnp-installer#30]
http://www.bay12forums.com/smf/index.php?topic=130792.msg4673081#msg4673081

Looks like the script found his old df_linux folder living in .local/share, recommended .local/share, and then upon failure, deleted .local/share assuming it was a top level df-lnp only folder. We took out this guy's keyrings, wesnoth saves, and more. :(

**Comment by andrewd18** [comment]
As part of the 0.4.0-dev branch, the amount of radical FS changes we're doing is reduced. All installation steps now install to a destination directory, which gets copied (not moved) to the install dir at the end of the script. Now any deletion and recreation of a folder is to a known-good folder.

See a62efc676991bd4444d1c23f2c9d56f09c89f900

**Comment by inilix** [comment]
Hey so this happened to me as well, I lost hours of work by trying to install your file into my documents folder and its completely gone. including your file.

**Comment by andrewd18** [comment]
Inilix, I'm very sorry that happened to you. I hope you had backups. :(

Pushing this and the other 0.4.0 dev changes out so hopefully this doesn't happen to anyone else.
