### ISSUE TITLE
don't require disabling system wide ptrace protection

### ISSUE THREAD

**Issue by maqifrnswa** [andrewd18/df-lnp-installer#32]
dwarftherapist doesn't work if it can't access df's memory.

However, you don't have to disable system wide ptrace protection as described
https://github.com/andrewd18/df-lnp-installer/wiki/Dwarf-Therapist-Cannot-Connect-to-Dwarf-Fortress

From: http://www.bay12forums.com/smf/index.php?topic=66525.msg3924827#msg3924827

you can instead:
sudo setcap cap_sys_ptrace=ep DwarfTherapist
to allow it to disable ptrace protection just for the dwarftherapist binary.

**Comment by andrewd18** [comment]
While I'm personally not convinced ptrace protection adds much, I'm willing to defer to the distro and this change makes sense. I'll make sure this gets in as part of 0.4.0.

Thanks for the bug report. :)

**Comment by coldmug** [comment]
I second this. I am of the opinion to allow people to bypass Dwarf Therapist. An app like that, no matter how good, is no reason to compromise the entire system.

**Comment by andrewd18** [comment]
Fixed in 0.5.0-dev branch. check_ptrace_protection now simply prints out a warning and gives the user a setcap command to run. The wiki page has also been updated.
