### ISSUE TITLE
disable terminal when launching soundsense

### ISSUE THREAD

**Issue by Ramblurr** [andrewd18/df-lnp-installer#37]
I prefer launching the LNP with `showTerminal: false` for soundsense. It reduces window clutter.

Any reason you left it enabled?

**Comment by andrewd18** [comment]
At one point it must have been enabled in the PeridexisErrant LNP for Windows, as that's where I poached the lnp.yaml config options from. I see that in his latest version (v40) that it's disabled so I'll go ahead and turn it off by default in my next release.

Unless you do an --upgrade after I patch this, you'll need to edit the lnp.yaml file yourself to see a change.

**Comment by andrewd18** [comment]
Resolved in 0.4.0-dev branch.
