### ISSUE TITLE
Add QuickFort and Chromafort mods

### ISSUE THREAD

**Issue by andrewd18** [andrewd18/df-lnp-installer#38]
Add the following mods, per the [Reddit discussion](http://www.reddit.com/r/dwarffortress/comments/1no1mn/lazy_newb_pack_for_linux_030/cckrk41).
- Chromafort
- Quickfort (and all the blueprints)

**Comment by PeridexisErrant** [comment]
I just opened an issue based on that discussion actually...  [here](https://github.com/andrewd18/df-lnp-installer/issues/39).  I've also updated the info and added some links.

**Comment by andrewd18** [comment]
Added to 0.5.0-dev branch.
