### ISSUE TITLE
Many Linux-compatible utilities are missing

### ISSUE THREAD

**Issue by PeridexisErrant** [andrewd18/df-lnp-installer#39]
Many more utilities could be included relatively easily.  Everything mentioned is linked [here](http://www.bay12forums.com/smf/index.php?topic=126076).  
- [Dfterm3](http://www.bay12forums.com/smf/index.php?topic=129995) 
- [Chromafort](http://www.bay12forums.com/smf/index.php?topic=55025)
- [Quickfort](http://www.bay12forums.com/smf/index.php?topic=35931) (and all [the blueprints](http://www.mediafire.com/df_qfcommunity))
- [DF Announcement Filter](http://www.bay12forums.com/smf/index.php?topic=130030)

There are also two batch scripts which could be ported to Linux.  [Dwarf Map Maker](http://www.bay12forums.com/smf/index.php?topic=73095.msg2261106#msg2261106) is a GIMP script called by a batch script, to make a pretty fantasy map from the legends exports.  My [legends processing script](http://dffd.wimbli.com/file.php?id=7989) includes that, and also handles compression and moving of all legends exports to a named folder; it would be relatively easy to port too.  

Extras - like DF settings, manuals, etc - don't need any setup and work on any platform. Embark profiles are already included and need to be listed under "included mods" in the readme.
- [Vherid's color schemes](http://www.bay12forums.com/smf/index.php?topic=89856)
- [Cheatsheets from Reddit](https://www.dropbox.com/sh/8akafeuqfsxth7t/U-zOsO7pNr)
- [Manual for Dwarf Therapist](http://dffd.wimbli.com/file.php?id=7889)

**Comment by andrewd18** [comment]
Mediafire and Dropbox require that you visit the page in a real web browser using cookies. This is because they track each person for ad revenue and hit metrics. Downloading any files hosted on Dropbox or Mediafire is not something I can easily automate.

This rules out the Cheatsheets, Vherid's color schemes, and the Quickfort blueprints.

**Comment by PeridexisErrant** [comment]
Until the GUI allows separately installing colour schemes, it's probably easiest to skip those.  I've contacted the author of the cheatsheets and the maintainer of the blueprint archive regarding rehosting, so they might be mirrored to DFFD in time for v0.6

**Comment by PeridexisErrant** [comment]
[Here's](http://dffd.wimbli.com/file.php?id=8185) a DFFD mirror of the blueprints, with permission.  

Edit:  and /u/spongemandan has mirrored the cheatsheets on DFFD [(here)](http://dffd.wimbli.com/file.php?id=8186)

**Comment by Ramblurr** [comment]
I added quickfort blueprints in #57

**Comment by BeauBouchard** [comment]
You could also use the API to have an actual dropbox account download, but then each user would need to enter the API key, or share one.
