### ISSUE TITLE
ptrace still creating problems

### ISSUE THREAD

**Issue by Alanba42** [andrewd18/df-lnp-installer#40]
I tried the ptrace solution you suggested, but still no luck getting Therapist to connect in Ubuntu Precise. Any suggestions?

**Comment by Alanba42** [comment]
It does work when I disable ptrace this way (from Bay 12 forums)

echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

**Comment by andrewd18** [comment]
Without more information as to what you tried and what the error messages were, I really can't help you.

**Comment by andrewd18** [comment]
Closing with NEEDINFO. Reopen as necessary.
