### ISSUE TITLE
Sha verification for "Dwarf Therapist.pdf" failed

### ISSUE THREAD

**Issue by tychotatitscheff** [andrewd18/df-lnp-installer#41]
Script failed sha-verifaication of "Dwarf Therapist.pdf"

Work perfecticly when invoqing instalation script with --skip-sha

**Comment by erikbgithub** [comment]
same here. skipping is a workaround, but probably something needs to be updated about this repository.

**Comment by lioobayoyo** [comment]
same here.

and also for  "Utility_Plugins_v0.36-Windows-0.34.11.r3.zip.zip"

**Comment by tchalvak** [comment]
Same thing happened to me, and I'm actually reading the Dwarf Therapist.pdf at the same time and it looks to be fine.

**Comment by andrewd18** [comment]
Resolved as of 0.5.1.
