### ISSUE TITLE
Readme for fedora and qmake

### ISSUE THREAD

**Issue by lioobayoyo** [andrewd18/df-lnp-installer#42]
qmake doesn't seem to exist in the fedora repos and neither in the rpmfusion (when i checked with 
yum what provides qmake
)
however qmake-qt4 is available in the qt-devel yum package

since you already check for qmake-qt4 in the install script,I'd suggest just adding a note to the installation instructions for fedora 19 users so they change qmake to qmake-qt4 in the command line provided to install the dependencies

thanks !

**Comment by andrewd18** [comment]
The README.md already has qt-devel listed as a package for Fedora. Note that the script itself only complains about missing files, not the packages you need on $DISTRO, because I cannot possibly predict every distribution's naming convention.
