### ISSUE TITLE
Recommend dependencies install syntax in the script failure errors?

### ISSUE THREAD

**Issue by tchalvak** [andrewd18/df-lnp-installer#43]
Error on ubuntu:

 ./df-lnp-installer.sh
Checking for dependencies...

df-lnp-installer.sh: Your computer is missing the following programs or libraries: unrar hg libQtCore libQtGui libQtNetwork libQtScript qmake_qt4 libOpenAL_1_(32-bit) libGTK-x11_(32-bit) libJPEG62_(32-bit) . Install them using your distribution's package manager or use --skip-deps to override. Exiting.

Perhaps it would make sense to just reference the dependency install command listed in the readme with a switch for the OS versions?

E.g. "You may try installing these on debian/ubuntu with: sudo apt-get blahblahblah" on dependency fail...

**Comment by andrewd18** [comment]
Because not everyone uses Ubuntu or Debian, I cannot recommend a specific set of commands for a user to run. The script says to use your package manager, and that should be generic enough.
