### ISSUE TITLE
cannot stat `./lnp.yaml': No such file or directory

### ISSUE THREAD

**Issue by ValentinPearce** [andrewd18/df-lnp-installer#49]
These are the two last lines I get after an installation attempt:

install: cannot stat `./lnp.yaml': No such file or directory

df-lnp-installer.sh: Copying LNP Yaml file failed. Exiting.

**Comment by andrewd18** [comment]
You seem to be missing the lnp.yaml file that is part of the repository. I suggest you re-download the latest tag or checkout the repository, then try again.

Alternately, you are not running the df-lnp-installer script from the directory it is placed in. Please `cd` to that directory before running it.

**Comment by ValentinPearce** [comment]
I had to cd in the directory. Thank you very much
