### ISSUE TITLE
LXLE 12.04.4 (Lubuntu 12.04.4) x64 - Install script aborts

### ISSUE THREAD

**Issue by gauzyosbourne** [andrewd18/df-lnp-installer#54]
Yes, I'm aware that there's a previous issue very similar to this, but I've tried everything and nothing has worked. First, I downloaded the df-lnp-installer-master.zip. I put it into a folder I titled DWARF (/home/[user]/DWARF). I then extracted the folder there and ran the .sh. When it asked me where I should install, I put in /home/[user]/DWARF/df-lnp-installer-master/DWARF (yes, another folder named DWARF). Everything seemed fine until:

abort: No such file or directory: ./downloads/dwarftherapist
Dwarf Therapist repo is missing or has wrong upstream URL; recloning.
adding changesets
adding manifests
adding file changes
added 574 changesets with 4506 changes to 787 files
updating to branch default
662 files updated, 0 files merged, 0 files removed, 0 files unresolved
Cloning into './downloads/quickfort'...
remote: Reusing existing pack: 2071, done.
remote: Total 2071 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2071/2071), 14.59 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (533/533), done.
sha1sum: sha1sums: No such file or directory

df-lnp-installer.sh: One or more file failed its checksum. Delete the erroring file from the ./downloads directory and try again. Exiting.

So it appears that not only am I having a similar error as another user regarding the sha1sum bit, but the dwarftherapist folder, which exists, is not being found by the script? Help?

**Comment by andrewd18** [comment]
You need to cd into the df-lnp-installer folder before you run the script.

**Comment by gauzyosbourne** [comment]
AHA, yes, silly me. Thanks! :)
