### ISSUE TITLE
Utility_Plugins_v0.43-Windows-0.34.11.r3.zip always fails checksum regardless of redownloads

### ISSUE THREAD

**Issue by Algorhythm-sxv** [andrewd18/df-lnp-installer#61]
installing LNP on Ubuntu, no matter how many times I re-ran the installer script and re-downloaded this file, it always failed the checksum. After commenting the checksum function out of the script, DF and LNP installed flawlessly.

**Comment by andrewd18** [comment]
The author probably updated the utility plugins and removed the old download. Had you read the usage section or the error messages, you would have been instructed to use --skip-sha.

I'll look into updating the checksum and/or utility plugin package. Thank you.

**Comment by ketsa** [comment]
Same problem here, I'm on Debian Jessie, it seems not only the checksum fails but the file is either corrupt or not a zip file at all ?

Here is what I get with --skip-sha

Archive:  ./downloads/Utility_Plugins_v0.43-Windows-0.34.11.r3.zip.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./downloads/Utility_Plugins_v0.43-Windows-0.34.11.r3.zip.zip or
        ./downloads/Utility_Plugins_v0.43-Windows-0.34.11.r3.zip.zip.zip, and cannot find ./downloads/Utility_Plugins_v0.43-Windows-0.34.11.r3.zip.zip.ZIP, period.

df-lnp-installer.sh: Unzipping Falconne UI plugins failed. Exiting.

**Comment by ketsa** [comment]
I found a solution that worked for me, in your script replace : 
"Utility_Plugins_v0.43" by 
"Utility_Plugins_v0.44" and it works. Seems like v0.43 was corrupt.

sha1sum of new version : "3ec47274fe71f02539ec18063cfa2da2da9bd278  Utility_Plugins_v0.44-Windows-0.34.11.r3.zip.zip"

**Comment by reloadfast** [comment]
@ketsa many thanks for the solution, worked too for me.
