### ISSUE TITLE
Falconne's plugins are up to v46

### ISSUE THREAD

**Issue by PeridexisErrant** [andrewd18/df-lnp-installer#68]
And an update usually breaks the checksums, causing errors.  This can be trivially fixed this time with pull #67  - but it's a regular event.  

As well as updating the script, I would consider an upgrade:  if the checksum fails, compare the version number and if greater than the checksum output a message like `checksum failed due to an update in the plugins` (or $component).  Depending on how errors are handled, you could also give an option to proceed despite the error or even do so even without the `--skip-sha` option when it is for a known reason.  Unfortunately my little scripting experience is limited to windows, or I'd give it a go myself.

**Comment by dorferino** [comment]
now up to v47

**Comment by Estevo-Aleixo** [comment]
There is no way to get the version string with the current way dffd works.

**Comment by PeridexisErrant** [comment]
No, there is - it's a hidden-ish page that holds the metadata in plain text.  I just can't remember the link format off the top of my head...

Ah, there we go:  you can click the grey "file version" link on the DFFD page, and you get something like:  http://dffd.wimbli.com/file_version.php?id=7248

```
Updated: 1402814689
Date: Jun 15, 2014, 11:44:49 pm
Version: 0.47
```

Not just the version string, but the time of last update!

**Comment by Estevo-Aleixo** [comment]
Aha I hadn't seen that.
