### ISSUE TITLE
Upgrade to DFHack-r5 and include the new Stonesense Overlay

### ISSUE THREAD

**Issue by PeridexisErrant** [andrewd18/df-lnp-installer#70]
I've recently added them to my pack, and I've lost track of the times just in the last two days when someone asks if it's available on Linux.  Luckily not too difficult to point here and at the [new DFHack thread](http://www.bay12forums.com/smf/index.php?topic=139553), but it could be put in.

**Comment by BeauBouchard** [comment]
the link to stonesense 0.34.11-r5 Linux http://dffd.wimbli.com/download.php?id=8689&f=stonesense+linux.7z

the link to dfhack 0.34.11-r5 Linux
http://dffd.wimbli.com/download.php?id=8681&f=dfhack-0.34.11-r5-Linux.tar.gz

I am still reading the script, will try to add them to a fork
