### ISSUE TITLE
ASCII Graphics should use ASCII Graphics

### ISSUE THREAD

**Issue by andrewd18** [andrewd18/df-lnp-installer#8]
The ASCII graphics should actually use ASCII graphics not a bmp pack. Follow PeridexisErrant's lead on this one:

> The other thing is an issue to be fixed in my next [Windows LNP] release - the ASCII default tileset should have graphics disabled by default, while all the others have it enabled.

**Comment by PeridexisErrant** [comment]
This is trivial to do given that you've already patched the init files - just set `[GRAPHICS:NO]` in the ASCII patch script.

**Comment by andrewd18** [comment]
Apparently this is already fixed as of 0.3.x. I'm good at this. <_<  Closing.
